spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: itCD1688!
    url: jdbc:mysql://114.215.253.101:3306/springcloud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx9a23d450418f669d
  mpAppSecret: 92c1bc2ac5a92d6725b1068933921175